coloclue/peering

peers.yaml
=> Add Fusix Networks AS 57866 @ AMS-IX

peers.yaml
Hi, I've added Pine Digital Security (AS12854) for peering. Sessions have been configured on our side.
=> Added AS12854 for peering

peers.yaml
Sessions are configured on AS2635 side. Could you please merge the pull request ?
=> Add Automattic Inc. (AS2635)

peers.yaml
Please add the peering for our AMS-IX routers.
=> Added Cambrium (AS25596)

peers.yaml
=> Add peering PCextreme

peers.yaml
=> Peering BICS (6774)

peers.yaml
=> Add Weservit B.V. AS198203

peers.yaml
Added PeakFactory AS49206. Sessions are configured on our end.
=> Add AS49206

README.md, peers.yaml
=> Add Asteroid route-servers

peers.yaml
As requested per your mail, let's peer :-)
Happy peering!
Best
Max
=> Add peering with AS201701 (Freifunk Rheinland e.V.)

peers.yaml
Hey there,
I'm peering at SPEED-IX and would like to setup a session
=> Add peering to AS60927

peers.yaml
Hi,
We're both present at SPEED-IX and I would like to peer!
Groutnes uut Grunn,
Rick
=> Peering with AS204526

peers.yaml
Fixed issues with prefix-limit numbers and static configs for the following peers:
AS2828
AS6453
AS3910
AS6762
AS12956
=> Fix small issues with several peers

peers.yaml
This PR adds me (AS57782) to peering via Speed-IX.
=> Add AS57782 peering

peers.yaml
=> add peering with Speakup

peers.yaml
Add a peering session with Paul Hoogsteder, aka meanie (AS31019).
=> Add AS31019

peers.yaml
Access2.IT Group B.V. (AS208258) requested a peering session with us, so I'm adding them to our peers.yaml
=> Add AS208258

peers.yaml
Moved the ASN of CIRA from AS55195 to AS394354
=> Updated the ASN of CIRA

peers.yaml
The RIPE:: part makes our automation crash, so I removed it from the AS-SET
=> Fix AS-SET AS201401

peers.yaml
See https://www.peeringdb.com/asn/213050
=> Add AS213050

peers.yaml
Serverion wants to peer with us, so I added an session for it
=> Add AS213035

peers.yaml, tests/test_peering_relations.py
We are also present on the LSIX now, so adding a connection to the LSIX route servers
=> Add LSIX routeservers

README.md, peers.yaml, tests/test_peering_relations.py
Let's put the DE-CIX link into production.
=> Add DE-CIX Route servers.

peers.yaml
Adding NetActuate Inc. (AS36236) because Sonia has aranged peering with them.
=> Add AS36236

peers.yaml
Solutions 4xs (AS209288) requested to peer with us, so I've added them to peers.yml
=> Add AS209288

peers.yaml
AS60557 is now the main AS of Alpine North
=> Added AS60557

peers.yaml
AS211827 wil peeren met ons, dus die voeg ik dan toe.
=> Add AS211827

peers.yaml
Adding NIKHEF (AS1104) to our peers.
=> Add AS1104

peers.yaml
Earthlink Telecommunications Equipment Trading & Services DMCC (AS60051) wants to peer, so let's set up these sessions
=> Add AS60051

peers.yaml
Use prefix limits from PeeringDB for AS3320
=> Use prefix limits from PeeringDB for AS3320

peers.yaml
=> Add AS16278

peers.yaml
Adding a session with MlaB (AS41047)
=> Add AS41047

peers.yaml
=> Add AS29169

peers.yaml
As discussed on IRC with Cybertinus.
=> Remove AS44654: no IXP in common.

peers.yaml
Added Apple Communications Ltd. and Sipartech SAS
=> Added Apple Communications Ltd. and Sipartech SAS

peers.yaml
Since I removed my server from the Coloclue network, we no longer have a peering session.
This fixes that :)
[PeeringDB](https://www.peeringdb.com/net/31130)
=> Add peering session with AS202585

peers.yaml
Peering request from AS59645 via INTERIX
=> Added AS59645

peers.yaml
=> Add AS45102

peers.yaml
Add AS20326 / Teraswitch to all IXs except SwissIX.
=> Add AS20326 / Teraswitch

peers.yaml
Evolink (EVOLINK AD, AS8262) has requested peering, so I added them.
=> Add AS8262
