coloclue/peering

peers.yaml

Adding peering for AS112 (run by RIPE NCC) at AMS-IX.
Cheers,
Colin

Adding AS112 peering at AMS-IX

---

peers.yaml

Since they are leaving the NL-IX and we don't have any other IXes in common, I've removed them.

Remove AS37353 (MacroLan)

---

peers.yaml
tests/test_peering_relations.py

Since we accept more routes then there are in the DFZ from them, we could disable this limit without issue.
This prevents issues in the future, when the DFZ grows beyond 700.000 routes.

Disable the IPv4 prefix limit on Level 3

---

peers.yaml

Using the new only_on feature, you can now specify on which router(s) of the IX the session should be set up.
This feature was requested by AS12654 (RIPE NCC RIS project) for who it doesn't make sense to peer on both NL-IX ports.

Only activate AS12654 on first NL-IX port

---

peers.yaml

AS37353 has decided to stay on the NL-IX a little bit longer, thus enabling the sessions again.

Added AS37353 again

---

peers.yaml

The WikiMedia foundation is merging their two ASNs into one, causing us to update the ASN to the new one.
*** NOTE ***
Note: This MUST NOT be merged before October 11th 00:00 UTC, because before that time the WikiMedia Foundation haven't reconfigured their end for this configuration. If we merge before that time, our sessions with the WikiMedia Foundation will go down or at lease become unstable.
So please, DO NOT merge before October 11th 00:00 UTC
*** ENDNOTE ***

Update the ASN for the WikiMedia foundation

---

peers.yaml

NFOrce Entertainment B.V. is reducing the amount of direct peering settings. Thus we don't peer on the AMS-IX anymore, only via the route servers.
We don't peer with the route servers on the NL-IX, thus those settings remain active.

Only peer with NFOrce via the NL-IX

---

peers.yaml

AS260 (Xconnect24) has been bought by GTT, so they are placed behind AS3257. Thus the direct session to AS260 can be removed.

Remove AS260 (Xconnect24)

---

peers.yaml

Remove AS8928 (Interoute) because they are moved behind AS3257 (GTT)

Remove AS8928 (Interoute)

---

peers.yaml

PeeringDB has the Tilaa data again, so enabling it again.

Enable Tilaa again

---

peers.yaml

We also see Tilaa via the AMS-IX Route Server, dedicated sessions aren't needed.

Remove Tilaa

---

peers.yaml

All peers for which the sessions are down for at least 24 hours are removed.

Remove peers with all sessions down

---

peers.yaml

Joey has removed his SPEED-IX definition from PeeringDB, resulting in no sessions in common anymore. I've disabled his peering definition now, so the checks complete succesfully again.

Temporalily disable Joey Network

---

peers.yaml

We're available at AMS-IX and soon at AsteroidIX AMS.
GitHub, Inc. is happy to peer with Coloclue.
ASN - 36459
IRR (ARIN, RIPE): AS-GITHUB
http://as36459.peeringdb.com/
NOC: noc@github.com
Contact: peering@github.com
- AMS-IX, Amsterdam -
Router 1:
80.249.213.114
2001:7F8:1::A503:6459:1

Peer with Github AS36459

---

peers.yaml

Cloudflare doesn't want to peer with us using their new second router on the NL-IX, so we have to switch to a static config for them, to be able to filter out the router a session won't be formed on anyway.

Create a static config for Cloudflare

---

peers.yaml

Level3 has decommissioned the private peering with us, thus removing the configuration from our routers.

Remove level3 peering

---

peers.yaml

I’ve disabled two peers temporarily, because they have no data on PeeringDB anymore. To get a valid peers.yaml again which completes the travis test, I’ve disabled them.
I have send an e-mail to both peers. When they reply the peering can be enabled, enabled and modified or removed.

Temporarily disable two peers

---

peers.yaml

Since AS20621 isn’t visible in the DFZ anymore, the session can be completely removed.

Remove AS20621

---

peers.yaml

Cambrium (AS25596) doesn't peer on SPEED-IX, so I added an option to peers.yml to exclude specific routers from setting up BGP sessions. The update for Kees itself which supports this option will follow shortly.

Disable peering to AS25596 via SPEED-IX

---

peers.yaml

It is easier in Kees to proces specific IXPs for the not_on functionality, so I switched the config for Cambrium (AS25596) to the new way of working.

Change to IXP instead of peer IPs for not_on

---

peers.yaml

Google is giving us a hard time for setting up sessions over Asteroid and SpeedIX, so let's just remove the sessions on them. They aren't established anyway.

Disable peering with Google on Asteroid and SpeedIX

---

peers.yaml

The static prefix limits for AS6453 aren't needed anymore, the correct values are on PeeringDB nowdays, so we can extract them from there.

Remove unneeded prefix limits for AS6453

---

peers.yaml

They don't peer anymore on AS1140, only some private peering, which Coloclue isn't. So this session is unneeded

Remove peering with AS1140 (SIDN)

---

peers.yaml

AS10310 (Yahoo) has decided to not directly peer on the NL-ix anymore. To not hammer their routers with needless BGP connection attempts I removed the sessions over the NL-ix towards them

Remove NL-ix sessions for AS10310 (Yahoo)

---

peers.yaml

AS15542 (ZeelandNet) now only lives behind AS15435 (Caiway), so direct peering is useless to have.

Remove AS15542 (ZeelandNet)

---

peers.yaml

Seacom is leaving the route servers, so we are setting up direct peering sessions with them, to remain the option to send traffic directly to them.

Add AS37100 (Seacom)

---

peers.yaml

Kees didn't accept the old way of specifying the AS-SET for AS37100 (Seacom), so updated it to one Kees does accept.

Update AS-SET for AS37100 (Seacom)

---

peers.yaml

We don't need to manually specify the prefix limits for CloudFlare, Kees can extract them automatically from PeeringDB. The ignore_peeringdb flag doesn't have influence on that.

Remove the fixed prefix limits for CloudFlare (AS13335)

---

peers.yaml

Sentia is now the owner of Amsio. I've renamed the session to reflect this merger. Also the AS-SET has been renamed, so this is something that needs to be done, to keep the IRR filters correct in the future.

Amsio is now part of Sentia, renamed the session

---

peers.yaml

AS49627 (Speakup) doesn't have IPv6 connectivity on their Speed-IX facing router, so this session will never start.

Exclude Speed-IX IPv6 with AS49627 (Speakup)

---

peers.yaml

Liberty Global found out that we already have a session with AS6830, so the session with AS59776 isn't needed. Thus, removing the session.

Remove the session with AS59776 (Liberty Global CDN)

---

peers.yaml

We don't have any IX-es in common anymore with marlinc (AS60927), thus removed the peer from the peerlist, because there is no point in having this peer in the list anymore

Remove AS60927

---

peers.yaml

We are temporary disconnected from NL-ix and we don't have an alternative peering point with you

remove peering with AS201701 (Freifunk Rheinland e.V)

---

peers.yaml

Kabel Deutschland (AS31334) has migrated to be fully behind Vodafone (AS3209). They are leaving the IXes with AS31334, thus removing the sessions

Remove AS31334

---

peers.yaml

The multihop source map needs to be disabled for the NBIP lab, because otherwise the loopback address of the router is used for the eBGP multihop session. This won't work, the eBGP address should be used. This flag disables the usage of the loopback address, and thus the eBGP source address will be used.

Disable the usuage of the multihop source map for the NBIP lab

---

peers.yaml

This BGP session might be the cause of the issues of today. Disabling it until further notice.

Temporarily disable the BGP session to the NBIP lab

---

peers.yaml

An ASN was configured for Freedom Internet, while they have an AS-SET. So I moved to configuration over to the AS-SET

Move Freedom Internet to the correct AS-SET

---

peers.yaml

AS47065 (Peering TestBed) has changed the AS-SET they use for their IP space since we started peering. Updated it to the correct one.

Update import filter for AS47065

---

peers.yaml

AS28876 has left the AMS-IX and now we don't have any IXes left in common. They are only active in Germany anymore, and we aren't, so I don't expect that we have an IX in common soon.

Remove AS28876

---

peers.yaml

LinkedIn has left the NL-ix and now we don't have any IXes in common anymore, so removing them from the peering list only makes sense now.

Remove AS14413 (LinkedIn)

---

peers.yaml

AS23393 (ISPrime / BelugaCDN) has announced to us that they will shutdown the peering session, I have thus removed the definition of this peer from the list above.

Remove AS23393

---

peers.yaml

AS37271 (Workonline) has disconnected from the NL-ix, and their peering policy states that they need a connection over 2 IXes. So, only via the AMS-IX isn't enough for them, so those sessions needs to be removed as wel. Doing that in this commit.

Remove AS37271

---

peers.yaml

Removing AS36459, because we don't have a IXP incommon with them anymore, resulting in failed tests when changing this file.

Remove AS36459

---

peers.yaml

Removed 4 specific peer addresses for AS54113 (Fastly inc.) because they are in different countries than our routers, and by Fastly's policy they don't go internationally over an IXP. Thus removing these 4 sessions from the list.

Don't connect internationally with AS54113

---

peers.yaml

AS20953 (info.nl) has left public peering on all IXPs, so I'm removing the peering sessions with them.

Remove AS20953

---

peers.yaml
tests/test_peering_relations.py

We have another IXP on which we connect, namely the Frys-IX. Now we are adding the Frys-IX Route servers, to check if we can fully connect to it.

Add the Frys-IX route servers

---

peers.yaml

TESTED:
Ran Kees' peering_filters to confirm correct route server peers are defined.

Add France-IX and SwissIX route servers.

---

peers.yaml

Speakup has added a working IPv6 config on their Speed-IX facing router, so now we can have peering via IPv6 as well.

Peer with 49627 via Speed-IX over IPv6

---

peers.yaml

Cloudflare has indicated that they also want to peer on the Speed-IX, so the restrictions to only set up sessions over the AMS-IX and NL-ix aren't needed anymore. They are removed now.

Remove restrictions from the Cloudflare sessions

---

peers.yaml

CloudFlare has a lot more connections than only AMS-IX and NL-ix and they told us in the past that they don't want to set up connections on those. So, I've restored the orignal restrictions and added the 2 Speed-IX ip addresses, because the do want to add sessions on the Speed-IX.

Restore the Cloudflare restrictions and add Speed-IX

---

peers.yaml

We currently get 486k prefixes from Telia (AS1299) and the limit was 500k, so that is getting close. Telia recommends setting the limit to 550k on their PeeringDB page, so I increased the prefix limit to that amount

Increase IPv4 limit for AS1299

---

.github/workflows/test_peers.yaml.yml

Peers.yaml isn't tested anymore via Travis for some reason. To get that test working again, I'm moving the test over to the Github Actions feature, which they launched since we started using Travis. This ensures the quality of the peers.yaml and prevents a Kees run from failing.

Test the peers.yaml again

---

README.md

We migrated from Travis to Github Actions, so the status badge needs to be updated as well.

Show the correct build status

---

peers.yaml

Bij een aantal ASses stond het ASN als import filter, terwijl ze gewoon een AS-SET gedefineerd hebben op PeeringDB. Dat AS-SET heb ik op diverse plekken dus ingesteld.

Import filters rechttrekken

---

peers.yaml

DataWeb no longer peers on the NL-ix and this is the only IX we had in common with them, thus removing them from peers.yaml, to clean up our BGP session lists.

Remove AS35332 (DataWeb)

---

peers.yaml

We don't have any IXes in common anymore with AS2828, because they merged/renamed to Verizon.

Remove AS2828

---

peers.yaml

We can only peer with Google over the NL-ix and AMS-IX, so filtering out all other IXes. Since we have a port on the DE-CIX, France-IX and SwissIX nowadays, these sessions need to be removed from the attempts to peer with Google.

Update Google peering

---

peers.yaml

AS12859 has given the signal that they don't want to peer on the DE-CIX. It doesn't make a lot of sense to peer on it anyway, since both AS8283 and AS12859 are Dutch ISPs

Don't peer with AS12859 on DE-CIX

---

tests/test_peering_relations.py

The Speed-IX has upgraded their IPv4 range from 185.1.95.0/24 to 185.1.222.0/23. We need to reflect this in the tests.

Update the Speed-IX test to their new iprange

---

peers.yaml

Google doesn't want to peer with us over the Frys-IX, so let's remove those sessions.

Don't peer with Google over the Frys-IX

---

peers.yaml

AS6724 (Strato) is now single homed behind AS8560, so no need to have a direct connection with them anymore. They have removed all information from PeeringDB anyway.

Remove AS6724

---

peers.yaml

AS48886 (CS Net) has published an AS-SET as well. Let's use that instead of their AS-number directly.

Update the AS-SET for AS48886

---

peers.yaml

This peer gets removed because we don't have any IXPs in common
anymore

Remove ChinaCache (AS63541).

---

peers.yaml

Strato has moved everything behind AS8560 and they want to set up a peering connection from AS8560 towards us, so I'm adding that ASN now.

Add AS8560 (IONOS SE)

---

peers.yaml

Added AS207176 (OpenFiber) because they responded positively on our peering request after three years :).

Add AS207176

---

peers.yaml

The maintenance performed by SpeakUp (AS49627) on their NL-ix connection has been completed. The sessions can be enabled again. Today 1 session will restore, the other one will become established next week

Enable AS49627 on NL-ix again

---

peers.yaml

We are not a fan of scenic routing, thus there will be no peering session with IPng via LocIX The Netherlands

Do not peer with AS8298 on the locix

---

peers.yaml

AS208258 (Access2.IT) has left the only IX we had in common, so removing them from our peering list.

Remove 208258

---

peers.yaml

Uping the prefix limit for AS1299, because we are hitting the limit. Should be fine for a while

Increase prefix limit for AS1299

---

peers.yaml

We don't have any IX in common with FusionMediaLimited (AS56647) in common anymore. They didn't clean up their PeeringDB record, so the sessions were still in place. The AMS-IX notified us that we were hitting the arp sponge at their end. The Speed-IX (the only other IX we had in common) IP didn't respond as well, so the decision was made to remove the peering sessions at our end

Remove AS56647

---

peers.yaml

We don't have any IXes in common anymore with AS211827/BNPICT. He hasn't have any IXes lilsted anymore on his PDB page. Thus removing this peer.

Remove AS211827

---

peers.yaml

SURF started rebranding from SURFnet to SURF a few years ago. Updating the name in our system to reflect this rebranding

Rename AS1103 from "SURFnet" to "SURF", second try

---

.github/workflows/test_peers.yaml.yml

Current CI runs still use (deprecated) Node12 actions.
Upgrade to more recent versions that use Node16 equivalents.
Note that the failed CI run is due to a peer (AS44654) that ColoClue no longer has an IXP in common with.

Update CI actions to Node16 versions.

---

peers.yaml

Accenture has acquired Sentia Netherlands B.V., so updating the name and AS-SET accordingly.

Rename Sentia to Accenture

---

README.md
peers.yaml
tests/test_peering_relations.py

Add another IXP.
Propose to only merge once:

Add INTERIX.

---

peers.yaml

AS3267 (RUNNET) has disconnected from the AMS-IX, and this is the only IX we peer with them. So I removed them from peers.yaml.

Remove AS3267

---

peers.yaml

AS25596 (Cambrium) is leaving the DFZ, so removing sessions with them.

Remove AS25596

---

peers.yaml

Companion peering manifest changes to the [KEES PR#53](https://github.com/coloclue/kees/pull/53).
Adds `blackhole_accept` for DE-CIX and Swiss-IX route servers per their (included) documentation.
Note that this also adds `blackhole_community` keys for DE-CIX, even though the KEES code does not (yet) process these; they are for future use.

Use RFC7999 BLACKHOLE community on DE-CIX and SwissIX.

---

peers.yaml

Rocket Fibre (AS31595) has removed all their Public Exchange points from PeeringDB, so we can't make a BGP session with them anymore. Thus removing the config entirely from our Peering list.

Remove AS31595

---

peers.yaml

AS112 is not just hosted at RIPE NCC anymore, it has more people invested in this project now. So, removing the obsolete description.

Remove description at AS112

---

peers.yaml

Increased IPv6 for AS1299 from 150,000 to 175,000, to have a better margin. IPv4 limits have been unchanged

Increase prefix limit for AS1299 further

---

peers.yaml

I misread a peering request e-mail. This is the wrong peering party, thus removing not requested peering.

Remove AS8262

---

peers.yaml

Removing T-2 (AS34779), because our peering session is down with them, and they stated that they don't want a direct peering session with us, so no need to keep them in peers.yaml.

Remove AS34779

---

peers.yaml

NFOrce Entertainment B.V. doesn't want to peer with us directly, and the peering is down anyway, so removing the direct sessions.

Remove AS43350

---

peers.yaml

TransIP is moving behind Team.Blue (AS48185) for BGP. They disabled their AMS-IX sessions today, NL-ix was already down. And we don't have sessions with them on another IXP. We do have fully connected sessions with Team.Blue already, so this TransIP definition is not needed anymore and we will exchange traffic with TransIP via Team.Blue

Remove TransIP (AS20857)
